# Generated by Django 4.0.5 on 2022-06-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_videomessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomessage',
            name='file',
        ),
        migrations.AddField(
            model_name='videomessage',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.member')),
            ],
        ),
    ]
